---
development:
  bitcoin_network: 'testnet3'
  # coin_join_uri: 'coinjoin://coinmux/filesystem'
  coin_join_uri: 'coinjoin://coinmux/p2p?identifier=coinjoins-development&bootstrap=coinjoin.coinmux.com:14141'
  webbtc_host: 'http://test.webbtc.com'

test:
  bitcoin_network: 'testnet3'
  coin_join_uri: 'coinjoin://coinmux/test'
  webbtc_host: 'http://webbtc.example.com'

production:
  bitcoin_network: 'mainnet'
  coin_join_uri: 'coinjoin://coinmux/p2p'
  webbtc_host: 'http://webbtc.com'
