---
development:
  bitcoin_network: 'testnet3'
  coin_join_uri: 'coinjoin://coin2coin/freenet?request_key=TODO&insert_key=TODO'
  webbtc_host: 'http://test.webbtc.com'

test:
  bitcoin_network: 'testnet3'
  coin_join_uri: 'coinjoin://coin2coin/test?identifier={"key":"test-key","can_insert":true,"can_request":true}'
  webbtc_host: 'http://webbtc.example.com'

production:
  bitcoin_network: 'mainnet'
  coin_join_uri: 'coinjoin://coin2coin/freenet?request_key=TODO&insert_key=TODO'
  webbtc_host: 'http://webbtc.com'
