---
development:
  bitcoin_network: 'testnet3'
  coin_join_uri: 'coinjoin://coin2coin/freenet?request_key=TODO&insert_key=TODO'

test:
  bitcoin_network: 'testnet3'
  coin_join_uri: 'coinjoin://coin2coin/freenet?request_key=request-test-key&insert_key=insert-test-key'

production:
  bitcoin_network: 'mainnet'
  coin_join_uri: 'coinjoin://coin2coin/freenet?request_key=TODO&insert_key=TODO'
